---
- hosts: exit03
  remote_user: root
  roles:
    - hardening
    - nusenu.relayor
  vars:
    tor_ports:
      - { orport: 443, dirport: 80 }
    tor_ips:
      - { ipv4: "104.223.123.98" }
      - { ipv4: "104.223.123.99" }
      - { ipv4: "104.223.123.100" }
      - { ipv4: "104.223.123.101" }

- hosts: pegasus
  remote_user: noisetor
  roles:
    - nusenu.relayor
  vars:
    tor_ExitRelay: false
    tor_maxPublicIPs: 1
    tor_ports:
      - { orport: 9000, dirport: 0 }
    tor_ips:
      - { ipv4: "192.195.83.134" }
     
- hosts: exit01
  remote_user: root
  roles:
    - hardening
    - nusenu.relayor
  vars:
    tor_ports:
      - { orport: 443, dirport: 80 }
    tor_ips:
      - { ipv4: "173.254.216.66" }
      - { ipv4: "173.254.216.67" }
      - { ipv4: "173.254.216.68" }
      - { ipv4: "173.254.216.69" }
    tor_package_state: latest
